# Probar la ruta principal
GET http://127.0.0.1:5000/

###

# Probar el acceso al panel de administración
GET http://127.0.0.1:5000/admin

###

# Probar el acceso al panel de usuario
GET http://127.0.0.1:5000/user

###

# Probar el acceso a la página de edición
GET http://127.0.0.1:5000/edit