### Probar GET /info
GET http://127.0.0.1:5000/info
Content-Type: application/json

###

### Probar POST /mensaje
POST http://127.0.0.1:5000/mensaje
Content-Type: application/json

{
    "mensaje": "Benyahir Y."
}
